name: cd-release-deploy

on:
  release:

jobs:
  deploy-stg:
    concurrency: 
      group: deploy-stg
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: https://prod.test.com
    steps:
    - name: Deploy to staging
      run: |
        echo "$GITHUB_REF"
        echo "$GITHUB_REF_NAME"
        sleep 10

  deploy-prod:
    concurrency: 
      group: deploy-prod
    needs: [deploy-stg]
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: https://prod.test.com
    steps:
    - name: Deploy to staging
      run: |
        echo "$GITHUB_REF"
        echo "$GITHUB_REF_NAME"
        sleep 10
