name: ci-master

on:
  push:
    branches:
      - master
    paths-ignore:
      - version

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - name: Install npm packages
      run: npm ci
    - name: Setup Git
      run: |
        git config user.name 'CI Pipeline'
        git config user.email 'test@test.com'
    - name: bump version
      run: npm version patch
    - name: Push latest version
      run: git push origin main --follow-tags