name: ci-master
concurrency: 
  group: master-build
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package-lock.json'
      - 'package.json'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - name: Install npm packages
      run: npm ci
    - name: Setup Git
      run: |
        git config user.name 'CI Pipeline'
        git config user.email 'test@test.com'
    - name: bump version
      run: |
        VER=minor
        git log $(git tag | tail -n 1)..HEAD | grep feature || VER=patch
        echo "$VER release"
        npm version $VER
    - name: Push latest version
      run: git push origin master --follow-tags