name: ci-master

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package-lock.json'
      - 'package.json'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - name: Install npm packages
      run: npm ci
    - name: Setup Git
      run: |
        git config user.name 'CI Pipeline'
        git config user.email 'test@test.com'
    - name: bump version
      run: |
        echo "LAST_TAG=$(git tag | tail -n 1)" >> $GITHUB_ENV
        echo $LAST_TAG
        echo "VER=minor" >> $GITHUB_ENV
        echo $VER
        git log $LAST_TAG..HEAD | grep feature || VER=patch
        npm version $VER
    - name: Push latest version
      run: git push origin master --follow-tags